// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package cubevs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type mvmtapDnsAllowKey struct {
	Prefixlen uint32
	Name      [256]int8
}

type mvmtapDnsAllowValue struct {
	NameLen  uint32
	Flags    uint8
	Reserved [3]uint8
}

type mvmtapDnsQueryState struct {
	DnsOff         uint32
	Ifindex        uint32
	Flags          uint16
	_              [2]byte
	Cursor         uint32
	LabelRemaining uint32
	DottedLen      uint32
	ReversePos     uint32
	Failed         bool
	Done           bool
	Name           [256]int8
	_              [2]byte
}

type mvmtapDnsQueryTrackKey struct {
	Ifindex    uint32
	ServerIp   uint32
	SourcePort uint16
	DnsId      uint16
	Reserved   uint32
	QnameHash  uint64
}

type mvmtapDnsQueryTrackValue struct {
	ExpiresAtNs uint64
	Flags       uint8
	Reserved    [7]uint8
}

type mvmtapDnsResponseState struct {
	DnsOff     uint32
	Ifindex    uint32
	ServerIp   uint32
	SourcePort uint16
	Reserved   uint16
}

type mvmtapIngressSession struct {
	Version  uint32
	VmIp     uint32
	VmPort   uint16
	Reserved [3]uint16
}

type mvmtapLpmKey struct {
	Prefixlen uint32
	Ip        uint32
}

type mvmtapMvmMeta struct {
	Version        uint32
	Ip             uint32
	Uuid           [64]uint8
	DnsPolicyFlags uint8
	Reserved       [55]uint8
}

type mvmtapMvmPort struct {
	Ifindex    uint32
	ListenPort uint16
	Reserved   uint16
}

type mvmtapNatSession struct {
	AccessTime  uint64
	NodeIfindex uint32
	NodeIp      uint32
	VmIfindex   uint32
	VmIp        uint32
	NodePort    uint16
	VmPort      uint16
	State       uint8
	ActiveClose uint8
	Reserved    [34]uint8
}

type mvmtapNetPolicyValueV2 struct {
	ExpiresAtNs uint64
	Flags       uint8
	Reserved    [7]uint8
}

type mvmtapSessionKey struct {
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Version  uint32
	Protocol uint8
	Reserved [3]uint8
}

type mvmtapSnatIp struct {
	Lock     struct{ Val uint32 }
	Ifindex  uint32
	Ip       uint32
	MaxPort  uint16
	Reserved uint16
}

// loadMvmtap returns the embedded CollectionSpec for mvmtap.
func loadMvmtap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MvmtapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mvmtap: %w", err)
	}

	return spec, err
}

// loadMvmtapObjects loads mvmtap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*mvmtapObjects
//	*mvmtapPrograms
//	*mvmtapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMvmtapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMvmtap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// mvmtapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mvmtapSpecs struct {
	mvmtapProgramSpecs
	mvmtapMapSpecs
	mvmtapVariableSpecs
}

// mvmtapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mvmtapProgramSpecs struct {
	DnsFinish     *ebpf.ProgramSpec `ebpf:"dns_finish"`
	DnsParseChunk *ebpf.ProgramSpec `ebpf:"dns_parse_chunk"`
	DnsRevChunk   *ebpf.ProgramSpec `ebpf:"dns_rev_chunk"`
	FromCube      *ebpf.ProgramSpec `ebpf:"from_cube"`
}

// mvmtapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mvmtapMapSpecs struct {
	AllowOutV2        *ebpf.MapSpec `ebpf:"allow_out_v2"`
	DenyOut           *ebpf.MapSpec `ebpf:"deny_out"`
	DnsAllow          *ebpf.MapSpec `ebpf:"dns_allow"`
	DnsAllowInner     *ebpf.MapSpec `ebpf:"dns_allow_inner"`
	DnsQueryScratch   *ebpf.MapSpec `ebpf:"dns_query_scratch"`
	DnsQueryState     *ebpf.MapSpec `ebpf:"dns_query_state"`
	DnsQueryTrack     *ebpf.MapSpec `ebpf:"dns_query_track"`
	DnsResponseState  *ebpf.MapSpec `ebpf:"dns_response_state"`
	DnsTailCalls      *ebpf.MapSpec `ebpf:"dns_tail_calls"`
	EgressSessions    *ebpf.MapSpec `ebpf:"egress_sessions"`
	IfindexToMvmmeta  *ebpf.MapSpec `ebpf:"ifindex_to_mvmmeta"`
	IngressSessions   *ebpf.MapSpec `ebpf:"ingress_sessions"`
	LocalPortMapping  *ebpf.MapSpec `ebpf:"local_port_mapping"`
	MvmipToIfindex    *ebpf.MapSpec `ebpf:"mvmip_to_ifindex"`
	NetPolicyInner    *ebpf.MapSpec `ebpf:"net_policy_inner"`
	RemotePortMapping *ebpf.MapSpec `ebpf:"remote_port_mapping"`
	SnatIplist        *ebpf.MapSpec `ebpf:"snat_iplist"`
}

// mvmtapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mvmtapVariableSpecs struct {
	Cubegw0Ifindex   *ebpf.VariableSpec `ebpf:"cubegw0_ifindex"`
	Cubegw0Ip        *ebpf.VariableSpec `ebpf:"cubegw0_ip"`
	Cubegw0MacaddrP1 *ebpf.VariableSpec `ebpf:"cubegw0_macaddr_p1"`
	Cubegw0MacaddrP2 *ebpf.VariableSpec `ebpf:"cubegw0_macaddr_p2"`
	MvmGatewayIp     *ebpf.VariableSpec `ebpf:"mvm_gateway_ip"`
	MvmInnerIp       *ebpf.VariableSpec `ebpf:"mvm_inner_ip"`
	MvmMacaddrP1     *ebpf.VariableSpec `ebpf:"mvm_macaddr_p1"`
	MvmMacaddrP2     *ebpf.VariableSpec `ebpf:"mvm_macaddr_p2"`
	NodegwMacaddrP1  *ebpf.VariableSpec `ebpf:"nodegw_macaddr_p1"`
	NodegwMacaddrP2  *ebpf.VariableSpec `ebpf:"nodegw_macaddr_p2"`
	NodenicIfindex   *ebpf.VariableSpec `ebpf:"nodenic_ifindex"`
	NodenicIp        *ebpf.VariableSpec `ebpf:"nodenic_ip"`
	NodenicMacaddrP1 *ebpf.VariableSpec `ebpf:"nodenic_macaddr_p1"`
	NodenicMacaddrP2 *ebpf.VariableSpec `ebpf:"nodenic_macaddr_p2"`
}

// mvmtapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMvmtapObjects or ebpf.CollectionSpec.LoadAndAssign.
type mvmtapObjects struct {
	mvmtapPrograms
	mvmtapMaps
	mvmtapVariables
}

func (o *mvmtapObjects) Close() error {
	return _MvmtapClose(
		&o.mvmtapPrograms,
		&o.mvmtapMaps,
	)
}

// mvmtapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMvmtapObjects or ebpf.CollectionSpec.LoadAndAssign.
type mvmtapMaps struct {
	AllowOutV2        *ebpf.Map `ebpf:"allow_out_v2"`
	DenyOut           *ebpf.Map `ebpf:"deny_out"`
	DnsAllow          *ebpf.Map `ebpf:"dns_allow"`
	DnsAllowInner     *ebpf.Map `ebpf:"dns_allow_inner"`
	DnsQueryScratch   *ebpf.Map `ebpf:"dns_query_scratch"`
	DnsQueryState     *ebpf.Map `ebpf:"dns_query_state"`
	DnsQueryTrack     *ebpf.Map `ebpf:"dns_query_track"`
	DnsResponseState  *ebpf.Map `ebpf:"dns_response_state"`
	DnsTailCalls      *ebpf.Map `ebpf:"dns_tail_calls"`
	EgressSessions    *ebpf.Map `ebpf:"egress_sessions"`
	IfindexToMvmmeta  *ebpf.Map `ebpf:"ifindex_to_mvmmeta"`
	IngressSessions   *ebpf.Map `ebpf:"ingress_sessions"`
	LocalPortMapping  *ebpf.Map `ebpf:"local_port_mapping"`
	MvmipToIfindex    *ebpf.Map `ebpf:"mvmip_to_ifindex"`
	NetPolicyInner    *ebpf.Map `ebpf:"net_policy_inner"`
	RemotePortMapping *ebpf.Map `ebpf:"remote_port_mapping"`
	SnatIplist        *ebpf.Map `ebpf:"snat_iplist"`
}

func (m *mvmtapMaps) Close() error {
	return _MvmtapClose(
		m.AllowOutV2,
		m.DenyOut,
		m.DnsAllow,
		m.DnsAllowInner,
		m.DnsQueryScratch,
		m.DnsQueryState,
		m.DnsQueryTrack,
		m.DnsResponseState,
		m.DnsTailCalls,
		m.EgressSessions,
		m.IfindexToMvmmeta,
		m.IngressSessions,
		m.LocalPortMapping,
		m.MvmipToIfindex,
		m.NetPolicyInner,
		m.RemotePortMapping,
		m.SnatIplist,
	)
}

// mvmtapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMvmtapObjects or ebpf.CollectionSpec.LoadAndAssign.
type mvmtapVariables struct {
	Cubegw0Ifindex   *ebpf.Variable `ebpf:"cubegw0_ifindex"`
	Cubegw0Ip        *ebpf.Variable `ebpf:"cubegw0_ip"`
	Cubegw0MacaddrP1 *ebpf.Variable `ebpf:"cubegw0_macaddr_p1"`
	Cubegw0MacaddrP2 *ebpf.Variable `ebpf:"cubegw0_macaddr_p2"`
	MvmGatewayIp     *ebpf.Variable `ebpf:"mvm_gateway_ip"`
	MvmInnerIp       *ebpf.Variable `ebpf:"mvm_inner_ip"`
	MvmMacaddrP1     *ebpf.Variable `ebpf:"mvm_macaddr_p1"`
	MvmMacaddrP2     *ebpf.Variable `ebpf:"mvm_macaddr_p2"`
	NodegwMacaddrP1  *ebpf.Variable `ebpf:"nodegw_macaddr_p1"`
	NodegwMacaddrP2  *ebpf.Variable `ebpf:"nodegw_macaddr_p2"`
	NodenicIfindex   *ebpf.Variable `ebpf:"nodenic_ifindex"`
	NodenicIp        *ebpf.Variable `ebpf:"nodenic_ip"`
	NodenicMacaddrP1 *ebpf.Variable `ebpf:"nodenic_macaddr_p1"`
	NodenicMacaddrP2 *ebpf.Variable `ebpf:"nodenic_macaddr_p2"`
}

// mvmtapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMvmtapObjects or ebpf.CollectionSpec.LoadAndAssign.
type mvmtapPrograms struct {
	DnsFinish     *ebpf.Program `ebpf:"dns_finish"`
	DnsParseChunk *ebpf.Program `ebpf:"dns_parse_chunk"`
	DnsRevChunk   *ebpf.Program `ebpf:"dns_rev_chunk"`
	FromCube      *ebpf.Program `ebpf:"from_cube"`
}

func (p *mvmtapPrograms) Close() error {
	return _MvmtapClose(
		p.DnsFinish,
		p.DnsParseChunk,
		p.DnsRevChunk,
		p.FromCube,
	)
}

func _MvmtapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mvmtap_x86_bpfel.o
var _MvmtapBytes []byte
