// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package cubevs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type nodenicDnsAllowKey struct {
	Prefixlen uint32
	Name      [256]int8
}

type nodenicDnsAllowValue struct {
	NameLen  uint32
	Flags    uint8
	Reserved [3]uint8
}

type nodenicDnsQueryState struct {
	DnsOff         uint32
	Ifindex        uint32
	Flags          uint16
	_              [2]byte
	Cursor         uint32
	LabelRemaining uint32
	DottedLen      uint32
	ReversePos     uint32
	Failed         bool
	Done           bool
	Name           [256]int8
	_              [2]byte
}

type nodenicDnsQueryTrackKey struct {
	Ifindex    uint32
	ServerIp   uint32
	SourcePort uint16
	DnsId      uint16
	Reserved   uint32
	QnameHash  uint64
}

type nodenicDnsQueryTrackValue struct {
	ExpiresAtNs uint64
	Flags       uint8
	Reserved    [7]uint8
}

type nodenicDnsResponseState struct {
	DnsOff     uint32
	Ifindex    uint32
	ServerIp   uint32
	SourcePort uint16
	Reserved   uint16
}

type nodenicIngressSession struct {
	Version  uint32
	VmIp     uint32
	VmPort   uint16
	Reserved [3]uint16
}

type nodenicLpmKey struct {
	Prefixlen uint32
	Ip        uint32
}

type nodenicMvmMeta struct {
	Version        uint32
	Ip             uint32
	Uuid           [64]uint8
	DnsPolicyFlags uint8
	Reserved       [55]uint8
}

type nodenicMvmPort struct {
	Ifindex    uint32
	ListenPort uint16
	Reserved   uint16
}

type nodenicNatSession struct {
	AccessTime  uint64
	NodeIfindex uint32
	NodeIp      uint32
	VmIfindex   uint32
	VmIp        uint32
	NodePort    uint16
	VmPort      uint16
	State       uint8
	ActiveClose uint8
	Reserved    [34]uint8
}

type nodenicNetPolicyValueV2 struct {
	ExpiresAtNs uint64
	Flags       uint8
	Reserved    [7]uint8
}

type nodenicSessionKey struct {
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Version  uint32
	Protocol uint8
	Reserved [3]uint8
}

type nodenicSnatIp struct {
	Lock     struct{ Val uint32 }
	Ifindex  uint32
	Ip       uint32
	MaxPort  uint16
	Reserved uint16
}

// loadNodenic returns the embedded CollectionSpec for nodenic.
func loadNodenic() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NodenicBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nodenic: %w", err)
	}

	return spec, err
}

// loadNodenicObjects loads nodenic and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nodenicObjects
//	*nodenicPrograms
//	*nodenicMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNodenicObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNodenic()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nodenicSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nodenicSpecs struct {
	nodenicProgramSpecs
	nodenicMapSpecs
	nodenicVariableSpecs
}

// nodenicProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nodenicProgramSpecs struct {
	DnsHandleResponseProg *ebpf.ProgramSpec `ebpf:"dns_handle_response_prog"`
	DnsResponseFinishProg *ebpf.ProgramSpec `ebpf:"dns_response_finish_prog"`
	FromWorld             *ebpf.ProgramSpec `ebpf:"from_world"`
}

// nodenicMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nodenicMapSpecs struct {
	AllowOutV2        *ebpf.MapSpec `ebpf:"allow_out_v2"`
	DenyOut           *ebpf.MapSpec `ebpf:"deny_out"`
	DnsAllow          *ebpf.MapSpec `ebpf:"dns_allow"`
	DnsAllowInner     *ebpf.MapSpec `ebpf:"dns_allow_inner"`
	DnsQueryScratch   *ebpf.MapSpec `ebpf:"dns_query_scratch"`
	DnsQueryState     *ebpf.MapSpec `ebpf:"dns_query_state"`
	DnsQueryTrack     *ebpf.MapSpec `ebpf:"dns_query_track"`
	DnsResponseState  *ebpf.MapSpec `ebpf:"dns_response_state"`
	DnsTailCalls      *ebpf.MapSpec `ebpf:"dns_tail_calls"`
	EgressSessions    *ebpf.MapSpec `ebpf:"egress_sessions"`
	IfindexToMvmmeta  *ebpf.MapSpec `ebpf:"ifindex_to_mvmmeta"`
	IngressSessions   *ebpf.MapSpec `ebpf:"ingress_sessions"`
	LocalPortMapping  *ebpf.MapSpec `ebpf:"local_port_mapping"`
	MvmipToIfindex    *ebpf.MapSpec `ebpf:"mvmip_to_ifindex"`
	NetPolicyInner    *ebpf.MapSpec `ebpf:"net_policy_inner"`
	RemotePortMapping *ebpf.MapSpec `ebpf:"remote_port_mapping"`
	SnatIplist        *ebpf.MapSpec `ebpf:"snat_iplist"`
}

// nodenicVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nodenicVariableSpecs struct {
	Cubegw0Ifindex   *ebpf.VariableSpec `ebpf:"cubegw0_ifindex"`
	Cubegw0Ip        *ebpf.VariableSpec `ebpf:"cubegw0_ip"`
	Cubegw0MacaddrP1 *ebpf.VariableSpec `ebpf:"cubegw0_macaddr_p1"`
	Cubegw0MacaddrP2 *ebpf.VariableSpec `ebpf:"cubegw0_macaddr_p2"`
	MvmGatewayIp     *ebpf.VariableSpec `ebpf:"mvm_gateway_ip"`
	MvmInnerIp       *ebpf.VariableSpec `ebpf:"mvm_inner_ip"`
	MvmMacaddrP1     *ebpf.VariableSpec `ebpf:"mvm_macaddr_p1"`
	MvmMacaddrP2     *ebpf.VariableSpec `ebpf:"mvm_macaddr_p2"`
	NodegwMacaddrP1  *ebpf.VariableSpec `ebpf:"nodegw_macaddr_p1"`
	NodegwMacaddrP2  *ebpf.VariableSpec `ebpf:"nodegw_macaddr_p2"`
	NodenicIfindex   *ebpf.VariableSpec `ebpf:"nodenic_ifindex"`
	NodenicIp        *ebpf.VariableSpec `ebpf:"nodenic_ip"`
	NodenicMacaddrP1 *ebpf.VariableSpec `ebpf:"nodenic_macaddr_p1"`
	NodenicMacaddrP2 *ebpf.VariableSpec `ebpf:"nodenic_macaddr_p2"`
}

// nodenicObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNodenicObjects or ebpf.CollectionSpec.LoadAndAssign.
type nodenicObjects struct {
	nodenicPrograms
	nodenicMaps
	nodenicVariables
}

func (o *nodenicObjects) Close() error {
	return _NodenicClose(
		&o.nodenicPrograms,
		&o.nodenicMaps,
	)
}

// nodenicMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNodenicObjects or ebpf.CollectionSpec.LoadAndAssign.
type nodenicMaps struct {
	AllowOutV2        *ebpf.Map `ebpf:"allow_out_v2"`
	DenyOut           *ebpf.Map `ebpf:"deny_out"`
	DnsAllow          *ebpf.Map `ebpf:"dns_allow"`
	DnsAllowInner     *ebpf.Map `ebpf:"dns_allow_inner"`
	DnsQueryScratch   *ebpf.Map `ebpf:"dns_query_scratch"`
	DnsQueryState     *ebpf.Map `ebpf:"dns_query_state"`
	DnsQueryTrack     *ebpf.Map `ebpf:"dns_query_track"`
	DnsResponseState  *ebpf.Map `ebpf:"dns_response_state"`
	DnsTailCalls      *ebpf.Map `ebpf:"dns_tail_calls"`
	EgressSessions    *ebpf.Map `ebpf:"egress_sessions"`
	IfindexToMvmmeta  *ebpf.Map `ebpf:"ifindex_to_mvmmeta"`
	IngressSessions   *ebpf.Map `ebpf:"ingress_sessions"`
	LocalPortMapping  *ebpf.Map `ebpf:"local_port_mapping"`
	MvmipToIfindex    *ebpf.Map `ebpf:"mvmip_to_ifindex"`
	NetPolicyInner    *ebpf.Map `ebpf:"net_policy_inner"`
	RemotePortMapping *ebpf.Map `ebpf:"remote_port_mapping"`
	SnatIplist        *ebpf.Map `ebpf:"snat_iplist"`
}

func (m *nodenicMaps) Close() error {
	return _NodenicClose(
		m.AllowOutV2,
		m.DenyOut,
		m.DnsAllow,
		m.DnsAllowInner,
		m.DnsQueryScratch,
		m.DnsQueryState,
		m.DnsQueryTrack,
		m.DnsResponseState,
		m.DnsTailCalls,
		m.EgressSessions,
		m.IfindexToMvmmeta,
		m.IngressSessions,
		m.LocalPortMapping,
		m.MvmipToIfindex,
		m.NetPolicyInner,
		m.RemotePortMapping,
		m.SnatIplist,
	)
}

// nodenicVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNodenicObjects or ebpf.CollectionSpec.LoadAndAssign.
type nodenicVariables struct {
	Cubegw0Ifindex   *ebpf.Variable `ebpf:"cubegw0_ifindex"`
	Cubegw0Ip        *ebpf.Variable `ebpf:"cubegw0_ip"`
	Cubegw0MacaddrP1 *ebpf.Variable `ebpf:"cubegw0_macaddr_p1"`
	Cubegw0MacaddrP2 *ebpf.Variable `ebpf:"cubegw0_macaddr_p2"`
	MvmGatewayIp     *ebpf.Variable `ebpf:"mvm_gateway_ip"`
	MvmInnerIp       *ebpf.Variable `ebpf:"mvm_inner_ip"`
	MvmMacaddrP1     *ebpf.Variable `ebpf:"mvm_macaddr_p1"`
	MvmMacaddrP2     *ebpf.Variable `ebpf:"mvm_macaddr_p2"`
	NodegwMacaddrP1  *ebpf.Variable `ebpf:"nodegw_macaddr_p1"`
	NodegwMacaddrP2  *ebpf.Variable `ebpf:"nodegw_macaddr_p2"`
	NodenicIfindex   *ebpf.Variable `ebpf:"nodenic_ifindex"`
	NodenicIp        *ebpf.Variable `ebpf:"nodenic_ip"`
	NodenicMacaddrP1 *ebpf.Variable `ebpf:"nodenic_macaddr_p1"`
	NodenicMacaddrP2 *ebpf.Variable `ebpf:"nodenic_macaddr_p2"`
}

// nodenicPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNodenicObjects or ebpf.CollectionSpec.LoadAndAssign.
type nodenicPrograms struct {
	DnsHandleResponseProg *ebpf.Program `ebpf:"dns_handle_response_prog"`
	DnsResponseFinishProg *ebpf.Program `ebpf:"dns_response_finish_prog"`
	FromWorld             *ebpf.Program `ebpf:"from_world"`
}

func (p *nodenicPrograms) Close() error {
	return _NodenicClose(
		p.DnsHandleResponseProg,
		p.DnsResponseFinishProg,
		p.FromWorld,
	)
}

func _NodenicClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nodenic_x86_bpfel.o
var _NodenicBytes []byte
